include:
  - path: app/connector/my_pg/compose.yaml
  - path: app/connector/my_graphql/compose.yaml
services:
  engine:
    build:
      context: engine
      dockerfile: Dockerfile.engine
      pull: true
    environment:
      AUTHN_CONFIG_PATH: /md/auth_config.json
      ENABLE_CORS: "true"
      ENABLE_SQL_INTERFACE: "true"
      INTROSPECTION_METADATA_FILE: /md/metadata.json
      METADATA_PATH: /md/open_dd.json
      OTLP_ENDPOINT: http://local.hasura.dev:4317
      DDN_CACHE_ENABLED: "true"
      DDN_CACHE_TTL: 300  # Cache expiration in seconds
      DDN_CACHE_BACKEND: redis  # Use Redis for caching
    extra_hosts:
      - local.hasura.dev:host-gateway
    labels:
      io.hasura.ddn.service-name: engine
    ports:
      - 3280:3000
  otel-collector:
    command:
      - --config=/etc/otel-collector-config.yaml
    # environment:
    #   HASURA_DDN_PAT: ${HASURA_DDN_PAT}
    image: otel/opentelemetry-collector:latest
    # depends_on:
    #   - loki
    ports:
      - 4317:4317
      - 4318:4318
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
  
  # otel-collector:
  #   image: otel/opentelemetry-collector:latest
  #   container_name: otel-collector
  #   volumes:
  #     - ./otel-collector-config.yaml:/etc/otel-config.yaml
  #   command: ["--config=/etc/otel-config.yaml"]
  #   ports:
  #     - "4317:4317"
  #     - "4318:4318"  # OTLP HTTP
  #   depends_on:
  #     - loki

  # containers for log collection and viewing (Grafana)
  # loki:
  #   image: grafana/loki:latest
  #   container_name: loki
  #   user: "1000:1000"
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/etc/loki/local-config.yaml
  #   volumes:
  #     - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3005:3000"
  #   depends_on:
  #     - loki
  #   volumes:
  #     - ./grafana-provisioning:/etc/grafana/provisioning

  # redis cache, only for Hasura DDN engine ONLY, no public access to it
  redis:
    image: cgr.dev/chainguard/redis:latest
    # ports:
    #   - "6379:6379"

networks:
  default:
    external:
      name: ddn