services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./init:/usr/share/elasticsearch/init
    entrypoint: >
      /bin/bash -c "elasticsearch-plugin install analysis-phonetic;
      /usr/local/bin/docker-entrypoint.sh"

  # DB IDE for PostgreSQL only
  pgadmin:
    container_name: pgadmin
    image:  dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.com
      PGADMIN_DEFAULT_PASSWORD: test123
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: postgres
    ports:
    - "8889:80"
    volumes:
      - ./pg-admin-setup/servers.json:/pgadmin4/servers.json

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.3
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  elastic_setup_data:
    image: curlimages/curl
    depends_on:
      - elasticsearch
    entrypoint: >
      /bin/bash -c "
      sleep 10;
      curl -X PUT 'http://elasticsearch:9200/demo' -H 'Content-Type: application/json' -d '{\"settings\": {\"number_of_shards\": 1}, \"mappings\": {\"properties\": {\"title\": {\"type\": \"text\"}}}}';
      curl -X POST 'http://elasticsearch:9200/demo/_doc/1' -H 'Content-Type: application/json' -d '{\"title\": \"Elasticsearch for Beginners\"}';
      curl -X POST 'http://elasticsearch:9200/demo/_doc/2' -H 'Content-Type: application/json' -d '{\"title\": \"Advanced Search in Elasticsearch\"}';
      curl -X POST 'http://elasticsearch:9200/demo/_doc/3' -H 'Content-Type: application/json' -d '{\"title\": \"Deploying Elasticsearch with Docker\"}';
      "

  kibana_setup:
    image: curlimages/curl
    depends_on:
      - kibana
    entrypoint: >
      /bin/bash -c "
      sleep 30;
      curl -X POST 'http://kibana:5601/api/saved_objects/index-pattern/demo-pattern' -H 'Content-Type: application/json' -H 'kbn-xsrf: true' -d '{\"attributes\": {\"title\": \"demo-*\", \"timeFieldName\": \"timestamp\"}}';
      curl -X POST 'http://kibana:5601/api/saved_objects/dashboard/demo-dashboard' -H 'Content-Type: application/json' -H 'kbn-xsrf: true' -d '{\"attributes\": {\"title\": \"Demo Dashboard\"}}';
      "

volumes:
  es_data:
